Converting Normal Types to pulumi.* types accept inputs.
joeduffy/pulumi-go-helmbase pull request #3
Opened 2022-05-12 22:59 UTC by rshade

I started to convert the standard types to pulumi.*Input types for a couple of tickets on nginx, and cert-manager

2022-05-12 23:02 UTC, rshade commented
@joeduffy @viveklak I need your advice on what to do with https://github.com/joeduffy/pulumi-go-helmbase/pull/3/files#diff-70f1ecb7be66d191151d77019a75ef0ba0404acdcbaf1aa630099ed46d208771R109, there some logic here I don't know what to do with: https://github.com/joeduffy/pulumi-go-helmbase/blob/master/base.go#L185

2022-05-13 00:33 UTC, viveklak commented
> @joeduffy @viveklak I need your advice on what to do with https://github.com/joeduffy/pulumi-go-helmbase/pull/3/files#diff-70f1ecb7be66d191151d77019a75ef0ba0404acdcbaf1aa630099ed46d208771R109, there some logic here I don't know what to do with: https://github.com/joeduffy/pulumi-go-helmbase/blob/master/base.go#L185

Not entirely sure we need the `pulumi` tag values handling for values since they are a bag anyway? A merge of the map should be sufficient? Perhaps I am missing the specifics of your question?

2022-05-13 18:22 UTC, viveklak requested changes

2022-05-13 18:22 UTC, viveklak commented on base.go
> +			}
I think you still also want to merge in the items from `values` (4th parameter to `InitDefaults`).

2022-05-13 18:22 UTC, viveklak commented on base.go
> +	delete(localMap, FieldHelmOptionsInput)
Seems it would be simpler to just move this to the apply block above before returning?

2022-05-13 18:22 UTC, viveklak commented on base.go
> +		args.Values.ToMapOutput().ApplyT(func(vals map[string]interface{}) map[string]interface{} {
```suggestion
		merged := args.Values.ApplyT(func(vals map[string]interface{}) map[string]interface{} {
```
And then on line 194 `args.Values = merged`?

I haven't checked the types and perhaps some conversions would be required...

2022-05-13 20:56 UTC, rshade commented
@viveklak and I hacked on it. We decided to leave it a map, and conquer it in a future release.

2022-05-13 20:58 UTC, rshade commented
```
Diagnostics:
  pulumi:pulumi:Stack (simple-cert-manager-ts-dev):
    I0513 15:52:53.221111   24105 request.go:665] Waited for 1.055818426s due to client-side throttling, not priority and fairness, request: GET:https://212.2.244.219:6443/apis/storage.k8s.io/v1?timeout=32s

Outputs:
    certManagerStatus: {
        appVersion: "v1.8.0"
        chart     : "cert-manager"
        name      : "cert-manager-helm-20d9a2d3"
        namespace : "sandbox-ns-0e1ef72a"
        revision  : 1
        status    : "deployed"
        version   : "v1.8.0"
    }

Resources:
    + 5 created

Duration: 59s
```

2022-05-13 21:30 UTC, viveklak approved these changes

2022-05-13 21:49 UTC, joeduffy approved these changes

2022-05-13 21:49 UTC, merged